const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  CONFLICT_ERROR_CODE,
  INTERNAL_SERVER_ERROR,
};
